# Data Reading and Preprocessing

In [ ]:
import warnings
warnings.filterwarnings("ignore")

import os
import timeit
from collections import defaultdict
from contextlib import redirect_stdout
from io import StringIO
from itertools import combinations

import pandas as pd
from scipy.stats import trim_mean

In [7]:
df = pd.read_csv(os.path.join("dataset", "Market_Basket_Optimisation_binarized.csv"))
print(df.info())
df.head(3)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7501 entries, 0 to 7500
Columns: 119 entries, almonds to zucchini
dtypes: int64(119)
memory usage: 6.8 MB
None

,almonds,antioxydant juice,asparagus,avocado,babies food,bacon,barbecue sauce,black tea,blueberries,body spray,...,turkey,vegetables mix,water spray,white wine,whole weat flour,whole wheat pasta,whole wheat rice,yams,yogurt cake,zucchini
0,1,1,0,1,0,0,0,0,0,0,...,0,1,0,0,1,0,0,1,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

**get_support** function evaluates the support value for a set given all the transactions.

In [8]:
def get_support(df: pd.DataFrame, itemset: set) -> float:

    if len(df) == 0:
        return 0.0

    return df.iloc[:, sorted(itemset)].all(axis=1).mean()



def test_get_support():
    # Create a DataFrame
    _df = pd.DataFrame(
        {
            "A": [1, 1, 0, 0, 1],
            "B": [1, 0, 1, 1, 0],
            "C": [0, 1, 0, 1, 1],
        }
    )

    # Test the function
    assert get_support(_df, {0}) == 0.6
    assert get_support(_df, {1}) == 0.6
    assert get_support(_df, {2}) == 0.6
    assert get_support(_df, {0, 1}) == 0.2
    assert get_support(_df, {0, 2}) == 0.4
    assert get_support(_df, {1, 2}) == 0.2
    assert get_support(_df, {0, 1, 2}) == 0.0

    print("All test cases passed!.")


# Run the test cases
test_get_support()

All test cases passed!.

In [9]:
def get_subsets(item_set):
    return [item_set - {item} for item in item_set]


def test_get_subsets():
    # Test case 1: Empty item set
    item_set_empty = set()
    expected_output_empty = []
    assert get_subsets(item_set_empty) == expected_output_empty

    # Test case 2: Non-empty item set
    item_set_non_empty = {1, 2, 3}
    expected_output_non_empty = [{2, 3}, {1, 3}, {1, 2}]
    assert get_subsets(
        item_set_non_empty) == expected_output_non_empty

    print("Test cases for get_subsets passed!")


test_get_subsets()

Test cases for get_subsets passed!

In [10]:
def is_valid_set(item_set, prev_level_sets):
    """ 
    Check if all the subsets of the item_set are present in the previous level sets.
    
    Parameters:
        item_set (list): The item set to be validated.
        prev_level_sets (list of lists): List of sets from the previous level.
        
    Returns:
        bool: True if all subsets of the item_set are present in prev_level_sets, False otherwise.
      
    Example:
        >>> prev_level_sets = [{1, 2}, {2, 3}, {1, 3}]
        >>> item_set = {1, 2, 4}
        in this example, a subset of item_set {1, 4} is not present in prev_level_sets.
        following the principle that if a set is not frequent, all its supersets are also not frequent,
        and since {1, 4} is not frequent, ie: not present in prev_level_sets, {1, 2, 4} is also not frequent.
    """
    if len(prev_level_sets) == 0:
        return False
    
    single_drop_subsets = get_subsets(item_set)
    for single_drop_set in single_drop_subsets:
        if single_drop_set not in prev_level_sets:
            return False
        
    return True


def test_is_valid_set():
    # Test case 1: Empty previous level sets
    prev_level_sets_empty = []
    item_set = {1, 2}
    assert is_valid_set(item_set, prev_level_sets_empty) is False

    # Test case 2: Item set not present in previous level sets
    prev_level_sets = [{3, 4}, {5, 6}]
    item_set_not_present = {1, 2}
    assert is_valid_set(item_set_not_present, prev_level_sets) is False

    # Test case 3: Item set present in previous level sets
    prev_level_sets_present = [{1, 2}, {2, 3}, {1, 3}, {3, 4}, {5, 6}]
    item_set_present = {1, 2, 3}
    assert is_valid_set(item_set_present, prev_level_sets_present) is True

    print("Test cases for is_valid_set passed!")


# Run the test cases
test_is_valid_set()

Test cases for is_valid_set passed!

**generate_candidate_item_sets** function generates the candidate item sets of size k from the frequent item sets of size k-1.

In [11]:
def generate_candidate_item_sets(frequent_item_sets, level):
    current_level_candidates = list()

    if len(frequent_item_sets[level - 1]) == 0:
        return current_level_candidates

    # Extract unique items from the frequent item sets of the previous level
    unique_items = set()
    prev_level_sets = list()
    for item_set, _ in frequent_item_sets[level - 1]:
        unique_items.update(item_set)
        prev_level_sets.append(item_set)

    # Generate candidates by combining unique items
    for candidate_set in combinations(unique_items, level + 1):
        # convert the tuple to a set
        candidate_set = set(candidate_set)
        # if the candidate set has a subset that doesn't exist in the frequent item sets of the previous level, skip it
        if is_valid_set(candidate_set, prev_level_sets):
            current_level_candidates.append(candidate_set)

    # calculate the support of each candidate set
    return current_level_candidates

**prune_candidates** function prunes the candidate sets evaluated based on the mean of the support for the current level.

In [ ]:
def prune_candidates(df: pd.DataFrame, current_level_candidates, trim_fraction=0.1):
    post_prune_candidates_set = list()

    supports = []
    for candidate_set in current_level_candidates:
        support = get_support(df, candidate_set)
        supports.append(support)
        post_prune_candidates_set.append((candidate_set, support))

    trimmed_mean_support = trim_mean(supports, proportiontocut=trim_fraction)

    return [
        (candidate_set, support)
        for candidate_set, support in post_prune_candidates_set
        if support >= trimmed_mean_support
    ], trimmed_mean_support


def test_prune_candidates():
    # Mock dataset
    data = {
        "A": [1, 1, 0, 0],
        "B": [1, 0, 1, 0],
        "C": [0, 1, 1, 0],
        "D": [1, 1, 1, 1],
    }
    df = pd.DataFrame(data)

    # Test case 1: Empty candidate set
    current_level_candidates = []
    expected_output_empty = []
    assert prune_candidates(df, current_level_candidates)[0] == expected_output_empty

    # Test case 2: Candidate set with valid itemsets
    current_level_candidates = [{0, 1}, {1, 2}, {2, 3}]
    
    expected_output_valid = [
        ({2, 3}, 0.5)
    ]
    assert prune_candidates(df, current_level_candidates)[0] == expected_output_valid

    print("All test cases passed!")


test_prune_candidates()

All test cases passed!

## Main apriori algorithm

In [ ]:
def apriori(df: pd.DataFrame, trimmed_mean_fraction=0.1):
    frequent_item_sets = defaultdict(list)
    history = pd.DataFrame(columns=["Level", "Candidates", "Frequent Itemsets", "Min Support"])

    means = df.mean()
    min_support = trim_mean(means, proportiontocut=trimmed_mean_fraction)

    for i, support in enumerate(means[means >= min_support]):
        frequent_item_sets[0].append(({i}, support))

    # Add the first row using loc
    history.loc[len(history)] = [0, len(df.columns), len(frequent_item_sets[0]), min_support]

    total_itemsets = 0
    for level in range(1, len(df.columns)):

        current_level_candidates = generate_candidate_item_sets(frequent_item_sets, level)

        if len(current_level_candidates) == 0:
            break

        frequent_item_sets[level], trimmed_mean_support = prune_candidates(
            df, current_level_candidates, trimmed_mean_fraction
        )
        num_frequent_itemsets = len(frequent_item_sets[level])
        total_itemsets += num_frequent_itemsets

        # Add each level's data to history using loc
        history.loc[len(history)] = [level, len(current_level_candidates), num_frequent_itemsets, trimmed_mean_support]

    return frequent_item_sets, history

In [48]:
trimmed_mean = 0.1
frequent_item_sets, history = apriori(df, trimmed_mean)
history

   Level  Candidates  Frequent Itemsets  Min Support
0    0.0       119.0               47.0     0.023876
1    1.0      1081.0              415.0     0.000622
2    2.0      2289.0             1093.0     0.000223
3    3.0      1403.0              411.0     0.000138
4    4.0        69.0               50.0     0.000236
5    5.0         2.0                2.0     0.000267

In [ ]:
num_iterations = 2

with redirect_stdout(StringIO()):
    time_taken = timeit.timeit(lambda: apriori(df), number=num_iterations)

print(f"Time taken for {num_iterations} iterations of apriori: {time_taken} seconds")

Time taken for 2 iterations of apriori: 27.94829629996093 seconds

## Generating Association Rules

In [28]:
item_support_dict = dict()

item_list = list()
for level in frequent_item_sets:
    for set_support_pair in frequent_item_sets[level]:
        for i in set_support_pair[0]:
            item_list.append(df.columns[i])
        item_support_dict[frozenset(item_list)] = set_support_pair[1]
        item_list = list()

In [29]:
item_support_dict

{frozenset({'almonds'}): 0.03332888948140248,
 frozenset({'antioxydant juice'}): 0.03372883615517931,
 frozenset({'asparagus'}): 0.0871883748833489,
 frozenset({'avocado'}): 0.030129316091187842,
 frozenset({'babies food'}): 0.08105585921877083,
 frozenset({'bacon'}): 0.025729902679642713,
 frozenset({'barbecue sauce'}): 0.04679376083188908,
 frozenset({'black tea'}): 0.05999200106652446,
 frozenset({'blueberries'}): 0.1638448206905746,
 frozenset({'body spray'}): 0.08038928142914278,
 frozenset({'bramble'}): 0.0510598586855086,
 frozenset({'brownies'}): 0.03186241834422077,
 frozenset({'bug spray'}): 0.17970937208372217,
 frozenset({'burger sauce'}): 0.027063058258898813,
 frozenset({'burgers'}): 0.026663111585121985,
 frozenset({'butter'}): 0.0793227569657379,
 frozenset({'cake'}): 0.1709105452606319,
 frozenset({'candy bars'}): 0.043060925209972005,
 frozenset({'carrots'}): 0.06332489001466471,
 frozenset({'cauliflower'}): 0.09532062391681109,
 frozenset({'cereals'}): 0.0523930142647647,
 frozenset({'champagne'}): 0.13211571790427942,
 frozenset({'chicken'}): 0.09825356619117451,
 frozenset({'chili'}): 0.026529796027196375,
 frozenset({'chocolate'}): 0.04946007199040128,
 frozenset({'chocolate bread'}): 0.047460338621517134,
 frozenset({'chutney'}): 0.03239568057592321,
 frozenset({'cider'}): 0.027196373816824423,
 frozenset({'clothes accessories'}): 0.07652313024930009,
 frozenset({'cookies'}): 0.12958272230369283,
 frozenset({'cooking oil'}): 0.23836821757099053,
 frozenset({'corn'}): 0.024130115984535395,
 frozenset({'cottage cheese'}): 0.0658578856152513,
 frozenset({'cream'}): 0.09505399280095987,
 frozenset({'dessert wine'}): 0.026529796027196375,
 frozenset({'eggplant'}): 0.028129582722303693,
 frozenset({'eggs'}): 0.04252766297826956,
 frozenset({'energy bar'}): 0.07145713904812692,
 frozenset({'energy drink'}): 0.05052659645380616,
 frozenset({'escalope'}): 0.17411011865084655,
 frozenset({'extra dark chocolate'}): 0.030395947207039063,
 frozenset({'flax seed'}): 0.06839088121583789,
 frozenset({'french fries'}): 0.06252499666711105,
 frozenset({'french wine'}): 0.025729902679642713,
 frozenset({'fresh bread'}): 0.029462738301559793,
 frozenset({'fresh tuna'}): 0.058525529929342755,
 frozenset({'fromage blanc'}): 0.027329689374750034,
 frozenset({'almonds', 'avocado'}): 0.0017331022530329288,
 frozenset({'almonds', 'black tea'}): 0.0009332089054792694,
 frozenset({'almonds', 'brownies'}): 0.0006665777896280496,
 frozenset({'almonds', 'burgers'}): 0.005199306759098787,
 frozenset({'almonds', 'butter'}): 0.0007998933475536596,
 frozenset({'almonds', 'cake'}): 0.0030662578322890282,
 frozenset({'almonds', 'carrots'}): 0.0009332089054792694,
 frozenset({'almonds', 'cereals'}): 0.0010665244634048793,
 frozenset({'almonds', 'champagne'}): 0.0006665777896280496,
 frozenset({'almonds', 'chicken'}): 0.0023996800426609784,
 frozenset({'almonds', 'chocolate'}): 0.005999200106652446,
 frozenset({'almonds', 'cookies'}): 0.0011998400213304892,
 frozenset({'almonds', 'cooking oil'}): 0.0017331022530329288,
 frozenset({'almonds', 'cottage cheese'}): 0.0007998933475536596,
 frozenset({'almonds', 'eggs'}): 0.006532462338354886,
 frozenset({'almonds', 'energy bar'}): 0.0007998933475536596,
 frozenset({'almonds', 'energy drink'}): 0.0007998933475536596,
 frozenset({'almonds', 'escalope'}): 0.0013331555792560992,
 frozenset({'almonds', 'french fries'}): 0.004399413411545127,
 frozenset({'almonds', 'french wine'}): 0.0013331555792560992,
 frozenset({'almonds', 'fresh bread'}): 0.0018664178109585388,
 frozenset({'almonds', 'fresh tuna'}): 0.001599786695107319,
 frozenset({'almonds', 'fromage blanc'}): 0.0007998933475536596,
 frozenset({'antioxydant juice', 'cereals'}): 0.0014664711371817091,
 frozenset({'antioxydant juice', 'chicken'}): 0.0006665777896280496,
 frozenset({'antioxydant juice', 'chocolate'}): 0.0014664711371817091,
 frozenset({'antioxydant juice', 'eggs'}): 0.0007998933475536596,
 frozenset({'antioxydant juice', 'escalope'}): 0.0010665244634048793,
 frozenset({'antioxydant juice', 'french fries'}): 0.0023996800426609784,
 frozenset({'antioxydant juice', 'fresh bread'}): 0.0006665777896280496,
 frozenset({'asparagus', 'burgers'}): 0.0006665777896280496,
 frozenset({'asparagus', 'chocolate'}): 0.0013331555792560992,
 frozenset({'asparagus', 'eggs'}): 0.0007998933475536596,
 frozenset({'asparagus', 'french fries'}): 0.0011998400213304892,
 frozenset({'avocado', 'barbecue sauce'}): 0.0006665777896280496,
 frozenset({'avocado', 'black tea'}): 0.0011998400213304892,
 frozenset({'avocado', 'body spray'}): 0.0010665244634048793,
 frozenset({'avocado', 'brownies'}): 0.0018664178109585388,
 frozenset({'avocado', 'burgers'}): 0.004532728969470737,
 frozenset({'avocado', 'butter'}): 0.0018664178109585388,
 frozenset({'avocado', 'cake'}): 0.004266097853619517,
 frozenset({'avocado', 'carrots'}): 0.0007998933475536596,
 frozenset({'avocado', 'cereals'}): 0.0014664711371817091,
 frozenset({'avocado', 'champagne'}): 0.001599786695107319,
 frozenset({'avocado', 'chicken'}): 0.0026663111585121984,
 frozenset({'avocado', 'chocolate'}): 0.007065724570057326,
 frozenset({'avocado', 'cider'}): 0.0006665777896280496,
 frozenset({'avocado', 'cookies'}): 0.0022663644847353685,
 frozenset({'avocado', 'cooking oil'}): 0.001999733368884149,
 frozenset({'avocado', 'cottage cheese'}): 0.0021330489268097585,
 frozenset({'avocado', 'eggs'}): 0.005599253432875617,
 frozenset({'avocado', 'energy bar'}): 0.0013331555792560992,
 frozenset({'avocado', 'energy drink'}): 0.0013331555792560992,
 frozenset({'avocado', 'escalope'}): 0.001599786695107319,
 frozenset({'avocado', 'french fries'}): 0.007998933475536596,
 frozenset({'avocado', 'french wine'}): 0.0006665777896280496,
 frozenset({'avocado', 'fresh bread'}): 0.0021330489268097585,
 frozenset({'avocado', 'fresh tuna'}): 0.001999733368884149,
 frozenset({'avocado', 'fromage blanc'}): 0.0007998933475536596,
 frozenset({'babies food', 'burgers'}): 0.0009332089054792694,
 frozenset({'babies food', 'chocolate'}): 0.0017331022530329288,
 frozenset({'babies food', 'cookies'}): 0.0009332089054792694,
 frozenset({'babies food', 'french fries'}): 0.0007998933475536596,
 frozenset({'bacon', 'barbecue sauce'}): 0.0011998400213304892,
 frozenset({'bacon', 'brownies'}): 0.0006665777896280496,
 frozenset({'bacon', 'burgers'}): 0.001999733368884149,
 frozenset({'bacon', 'butter'}): 0.0007998933475536596,
 frozenset({'bacon', 'cake'}): 0.0009332089054792694,
 frozenset({'bacon', 'chicken'}): 0.0011998400213304892,
 frozenset({'bacon', 'chocolate'}): 0.001999733368884149,
 frozenset({'bacon', 'cooking oil'}): 0.001599786695107319,
 frozenset({'bacon', 'eggplant'}): 0.0007998933475536596,
 frozenset({'bacon', 'eggs'}): 0.0029329422743634183,
 frozenset({'bacon', 'french fries'}): 0.0022663644847353685,
 frozenset({'barbecue sauce', 'black tea'}): 0.0006665777896280496,
 frozenset({'barbecue sauce', 'burgers'}): 0.001999733368884149,
 frozenset({'barbecue sauce', 'butter'}): 0.0011998400213304892,
 frozenset({'barbecue sauce', 'cake'}): 0.0010665244634048793,
 frozenset({'barbecue sauce', 'chicken'}): 0.0007998933475536596,
 frozenset({'barbecue sauce', 'chocolate'}): 0.0017331022530329288,
 frozenset({'barbecue sauce', 'cookies'}): 0.0009332089054792694,
 frozenset({'barbecue sauce', 'cooking oil'}): 0.0011998400213304892,
 frozenset({'barbecue sauce', 'eggplant'}): 0.0006665777896280496,
 frozenset({'barbecue sauce', 'eggs'}): 0.0035995200639914677,
 frozenset({'barbecue sauce', 'escalope'}): 0.0009332089054792694,
 frozenset({'barbecue sauce', 'french fries'}): 0.0017331022530329288,
 frozenset({'barbecue sauce', 'fresh bread'}): 0.0007998933475536596,
 frozenset({'black tea', 'burgers'}): 0.0022663644847353685,
 frozenset({'black tea', 'cake'}): 0.0018664178109585388,
 frozenset({'black tea', 'cereals'}): 0.0006665777896280496,
 frozenset({'black tea', 'champagne'}): 0.0006665777896280496,
 frozenset({'black tea', 'chicken'}): 0.0017331022530329288,
 frozenset({'black tea', 'chocolate'}): 0.0027996267164378083,
 frozenset({'black tea', 'cookies'}): 0.0007998933475536596,
 frozenset({'black tea', 'cooking oil'}): 0.0009332089054792694,
 frozenset({'black tea', 'cottage cheese'}): 0.0010665244634048793,
 frozenset({'black tea', 'eggs'}): 0.004932675643247567,
 frozenset({'black tea', 'escalope'}): 0.0009332089054792694,
 frozenset({'black tea', 'extra dark chocolate'}): 0.0006665777896280496,
 frozenset({'black tea', 'french fries'}): 0.0013331555792560992,
 frozenset({'black tea', 'french wine'}): 0.0013331555792560992,
 frozenset({'black tea', 'fresh bread'}): 0.0007998933475536596,
 frozenset({'black tea', 'fresh tuna'}): 0.0009332089054792694,
 frozenset({'blueberries', 'burger sauce'}): 0.0006665777896280496,
 frozenset({'blueberries', 'burgers'}): 0.0009332089054792694,
 frozenset({'blueberries', 'cake'}): 0.0007998933475536596,
 frozenset({'blueberries', 'champagne'}): 0.0006665777896280496,
 frozenset({'blueberries', 'chicken'}): 0.0011998400213304892,
 frozenset({'blueberries', 'chocolate'}): 0.0021330489268097585,
 frozenset({'blueberries', 'cookies'}): 0.0007998933475536596,
 frozenset({'blueberries', 'cooking oil'}): 0.0011998400213304892,
 frozenset({'blueberries', 'eggs'}): 0.0021330489268097585,
 frozenset({'blueberries', 'escalope'}): 0.0017331022530329288,
 frozenset({'blueberries', 'french fries'}): 0.0011998400213304892,
 frozenset({'blueberries', 'fresh bread'}): 0.0007998933475536596,
 frozenset({'body spray', 'brownies'}): 0.0009332089054792694,
 frozenset({'body spray', 'burgers'}): 0.0013331555792560992,
 frozenset({'body spray', 'butter'}): 0.0007998933475536596,
 frozenset({'body spray', 'cake'}): 0.0010665244634048793,
 frozenset({'body spray', 'champagne'}): 0.0007998933475536596,
 frozenset({'body spray', 'chicken'}): 0.0010665244634048793,
 frozenset({'body spray', 'chocolate'}): 0.0022663644847353685,
 frozenset({'body spray', 'eggs'}): 0.0022663644847353685,
 frozenset({'body spray', 'energy bar'}): 0.0006665777896280496,
 frozenset({'body spray', 'energy drink'}): 0.0010665244634048793,
 frozenset({'body spray', 'escalope'}): 0.0007998933475536596,
 frozenset({'body spray', 'french fries'}): 0.004266097853619517,
 frozenset({'body spray', 'fresh bread'}): 0.0006665777896280496,
 frozenset({'brownies', 'burgers'}): 0.003332888948140248,
 frozenset({'brownies', 'butter'}): 0.0014664711371817091,
 frozenset({'brownies', 'cake'}): 0.005465937874950006,
 frozenset({'brownies', 'cereals'}): 0.001599786695107319,
 frozenset({'brownies', 'champagne'}): 0.0011998400213304892,
 frozenset({'brownies', 'chicken'}): 0.0026663111585121984,
 frozenset({'brownies', 'chocolate'}): 0.004932675643247567,
 frozenset({'brownies', 'cider'}): 0.0006665777896280496,
 frozenset({'brownies', 'cookies'}): 0.0025329956005865884,
 frozenset({'brownies', 'cooking oil'}): 0.0029329422743634183,
 frozenset({'brownies', 'cottage cheese'}): 0.0034662045060658577,
 frozenset({'brownies', 'eggplant'}): 0.0011998400213304892,
 frozenset({'brownies', 'eggs'}): 0.007332355685908546,
 frozenset({'brownies', 'energy bar'}): 0.001999733368884149,
 frozenset({'brownies', 'energy drink'}): 0.0026663111585121984,
 frozenset({'brownies', 'escalope'}): 0.001599786695107319,
 frozenset({'brownies', 'extra dark chocolate'}): 0.0006665777896280496,
 frozenset({'brownies', 'french fries'}): 0.007865617917610986,
 frozenset({'brownies', 'french wine'}): 0.0014664711371817091,
 frozenset({'brownies', 'fresh bread'}): 0.0021330489268097585,
 frozenset({'brownies', 'fresh tuna'}): 0.0014664711371817091,
 frozenset({'brownies', 'fromage blanc'}): 0.0009332089054792694,
 frozenset({'bug spray', 'burgers'}): 0.0010665244634048793,
 frozenset({'bug spray', 'butter'}): 0.0006665777896280496,
 frozenset({'bug spray', 'cake'}): 0.0006665777896280496,
 frozenset({'bug spray', 'chicken'}): 0.001599786695107319,
 frozenset({'bug spray', 'chocolate'}): 0.001599786695107319,
 frozenset({'bug spray', 'cooking oil'}): 0.0006665777896280496,
 frozenset({'bug spray', 'eggs'}): 0.001599786695107319,
 frozenset({'bug spray', 'escalope'}): 0.0011998400213304892,
 frozenset({'bug spray', 'french fries'}): 0.0014664711371817091,
 frozenset({'burger sauce', 'cake'}): 0.0009332089054792694,
 frozenset({'burger sauce', 'chicken'}): 0.001599786695107319,
 frozenset({'burger sauce', 'chocolate'}): 0.0013331555792560992,
 frozenset({'burger sauce', 'cooking oil'}): 0.0006665777896280496,
 frozenset({'burger sauce', 'eggs'}): 0.001599786695107319,
 frozenset({'burger sauce', 'escalope'}): 0.0006665777896280496,
 frozenset({'burger sauce', 'french fries'}): 0.0010665244634048793,
 frozenset({'burger sauce', 'fresh bread'}): 0.0007998933475536596,
 frozenset({'burgers', 'butter'}): 0.0030662578322890282,
 frozenset({'burgers', 'cake'}): 0.011465137981602452,
 frozenset({'burgers', 'carrots'}): 0.0026663111585121984,
 frozenset({'burgers', 'cereals'}): 0.0034662045060658577,
 frozenset({'burgers', 'champagne'}): 0.0038661511798426876,
 frozenset({'burgers', 'chicken'}): 0.006265831222503666,
 frozenset({'burgers', 'chocolate'}): 0.017064391414478068,
 frozenset({'burgers', 'cider'}): 0.0021330489268097585,
 frozenset({'burgers', 'cookies'}): 0.005599253432875617,
 frozenset({'burgers', 'cooking oil'}): 0.005732568990801226,
 frozenset({'burgers', 'corn'}): 0.0011998400213304892,
 frozenset({'burgers', 'cottage cheese'}): 0.003332888948140248,
 frozenset({'burgers', 'dessert wine'}): 0.0007998933475536596,
 frozenset({'burgers', 'eggplant'}): 0.0014664711371817091,
 frozenset({'burgers', 'eggs'}): 0.02879616051193174,
 frozenset({'burgers', 'energy bar'}): 0.0027996267164378083,
 frozenset({'burgers', 'energy drink'}): 0.0017331022530329288,
 frozenset({'burgers', 'escalope'}): 0.007065724570057326,
 frozenset({'burgers', 'extra dark chocolate'}): 0.0009332089054792694,
 frozenset({'burgers', 'flax seed'}): 0.0011998400213304892,
 frozenset({'burgers', 'french fries'}): 0.021997067057725635,
 frozenset({'burgers', 'french wine'}): 0.0041327822956939075,
 frozenset({'burgers', 'fresh bread'}): 0.003999466737768298,
 frozenset({'burgers', 'fresh tuna'}): 0.0035995200639914677,
 frozenset({'burgers', 'fromage blanc'}): 0.0021330489268097585,
 frozenset({'butter', 'cake'}): 0.0029329422743634183,
 frozenset({'butter', 'carrots'}): 0.0011998400213304892,
 frozenset({'butter', 'cereals'}): 0.0010665244634048793,
 frozenset({'butter', 'chicken'}): 0.004266097853619517,
 frozenset({'butter', 'chocolate'}): 0.008265564591387815,
 frozenset({'butter', 'cookies'}): 0.0018664178109585388,
 frozenset({'butter', 'cooking oil'}): 0.0030662578322890282,
 frozenset({'butter', 'cottage cheese'}): 0.0010665244634048793,
 frozenset({'butter', 'eggs'}): 0.0061325156645780565,
 frozenset({'butter', 'energy bar'}): 0.0009332089054792694,
 frozenset({'butter', 'energy drink'}): 0.0009332089054792694,
 frozenset({'butter', 'escalope'}): 0.001599786695107319,
 frozenset({'butter', 'flax seed'}): 0.0006665777896280496,
 frozenset({'butter', 'french fries'}): 0.0061325156645780565,
 frozenset({'butter', 'french wine'}): 0.0010665244634048793,
 frozenset({'butter', 'fresh bread'}): 0.0021330489268097585,
 frozenset({'butter', 'fresh tuna'}): 0.0009332089054792694,
 frozenset({'cake', 'carrots'}): 0.0014664711371817091,
 frozenset({'cake', 'cereals'}): 0.0030662578322890282,
 frozenset({'cake', 'champagne'}): 0.0021330489268097585,
 frozenset({'cake', 'chicken'}): 0.006532462338354886,
 frozenset({'cake', 'chili'}): 0.0009332089054792694,
 frozenset({'cake', 'chocolate'}): 0.013598186908412212,
 frozenset({'cake', 'chocolate bread'}): 0.0006665777896280496,
 frozenset({'cake', 'cider'}): 0.0014664711371817091,
 frozenset({'cake', 'clothes accessories'}): 0.0006665777896280496,
 frozenset({'cake', 'cookies'}): 0.003999466737768298,
 frozenset({'cake', 'cooking oil'}): 0.004932675643247567,
 frozenset({'cake', 'cottage cheese'}): 0.004399413411545127,
 frozenset({'cake', 'eggplant'}): 0.0017331022530329288,
 frozenset({'cake', 'eggs'}): 0.019064124783362217,
 frozenset({'cake', 'energy bar'}): 0.003199573390214638,
 frozenset({'cake', 'energy drink'}): 0.0035995200639914677,
 frozenset({'cake', 'escalope'}): 0.0041327822956939075,
 frozenset({'cake', 'extra dark chocolate'}): 0.0007998933475536596,
 frozenset({'cake', 'flax seed'}): 0.0009332089054792694,
 frozenset({'cake', 'french fries'}): 0.01786428476203173,
 frozenset({'cake', 'french wine'}): 0.0017331022530329288,
 frozenset({'cake', 'fresh bread'}): 0.004399413411545127,
 frozenset({'cake', 'fresh tuna'}): 0.0037328356219170776,
 frozenset({'cake', 'fromage blanc'}): 0.0023996800426609784,
 frozenset({'candy bars', 'chocolate'}): 0.0009332089054792694,
 frozenset({'candy bars', 'eggs'}): 0.0010665244634048793,
 frozenset({'candy bars', 'french fries'}): 0.0011998400213304892,
 frozenset({'candy bars', 'fresh bread'}): 0.0007998933475536596,
 frozenset({'carrots', 'cereals'}): 0.0009332089054792694,
 frozenset({'carrots', 'champagne'}): 0.0006665777896280496,
 frozenset({'carrots', 'chicken'}): 0.0013331555792560992,
 frozenset({'carrots', 'chocolate'}): 0.0034662045060658577,
 frozenset({'carrots', 'cookies'}): 0.0006665777896280496,
 frozenset({'carrots', 'cooking oil'}): 0.0013331555792560992,
 frozenset({'carrots', 'cottage cheese'}): 0.0009332089054792694,
 frozenset({'carrots', 'eggplant'}): 0.0006665777896280496,
 frozenset({'carrots', 'eggs'}): 0.0029329422743634183,
 frozenset({'carrots', 'escalope'}): 0.001599786695107319,
 frozenset({'carrots', 'french fries'}): 0.0025329956005865884,
 frozenset({'carrots', 'fromage blanc'}): 0.0006665777896280496,
 frozenset({'cauliflower', 'chocolate'}): 0.0007998933475536596,
 frozenset({'cauliflower', 'eggs'}): 0.0010665244634048793,
 frozenset({'cauliflower', 'french fries'}): 0.0009332089054792694,
 frozenset({'cereals', 'champagne'}): 0.001999733368884149,
 frozenset({'cereals', 'chicken'}): 0.0026663111585121984,
 frozenset({'cereals', 'chocolate'}): 0.005599253432875617,
 frozenset({'cereals', 'chutney'}): 0.0006665777896280496,
 frozenset({'cereals', 'cookies'}): 0.0006665777896280496,
 frozenset({'cereals', 'cooking oil'}): 0.0029329422743634183,
 frozenset({'cereals', 'cottage cheese'}): 0.0011998400213304892,
 frozenset({'cereals', 'eggplant'}): 0.0009332089054792694,
 frozenset({'cereals', 'eggs'}): 0.0037328356219170776,
 frozenset({'cereals', 'energy bar'}): 0.0006665777896280496,
 frozenset({'cereals', 'energy drink'}): 0.0010665244634048793,
 frozenset({'cereals', 'escalope'}): 0.001599786695107319,
 frozenset({'cereals', 'french fries'}): 0.004799360085321957,
 frozenset({'cereals', 'french wine'}): 0.0011998400213304892,
 frozenset({'cereals', 'fresh bread'}): 0.0027996267164378083,
 frozenset({'cereals', 'fresh tuna'}): 0.0011998400213304892,
 frozenset({'cereals', 'fromage blanc'}): 0.0010665244634048793,
 frozenset({'champagne', 'chicken'}): 0.0025329956005865884,
 frozenset({'champagne', 'chocolate'}): 0.011598453539528063,
 frozenset({'champagne', 'cookies'}): 0.0037328356219170776,
 frozenset({'champagne', 'cooking oil'}): 0.0017331022530329288,
 frozenset({'champagne', 'cottage cheese'}): 0.001599786695107319,
 frozenset({'champagne', 'dessert wine'}): 0.0006665777896280496,
 frozenset({'champagne', 'eggs'}): 0.006665777896280496,
 frozenset({'champagne', 'energy bar'}): 0.0010665244634048793,
 frozenset({'champagne', 'energy drink'}): 0.0009332089054792694,
 frozenset({'champagne', 'escalope'}): 0.003999466737768298,
 frozenset({'champagne', 'french fries'}): 0.009332089054792695,
 frozenset({'champagne', 'french wine'}): 0.0013331555792560992,
 frozenset({'champagne', 'fresh bread'}): 0.0026663111585121984,
 frozenset({'champagne', 'fresh tuna'}): 0.0013331555792560992,
 frozenset({'chicken', 'chili'}): 0.0011998400213304892,
 frozenset({'chicken', 'chocolate'}): 0.014664711371817091,
 frozenset({'chicken', 'chocolate bread'}): 0.0007998933475536596,

## association_rules 
generates the association rules in accordance with the given _minimum confidence_ value and the provided dictionary of itemsets against their support values. For itemsets of more than one element, it first finds all their subsets. For every subset A, it calculates the set B = itemset-A. If B is not empty, the confidence of B is calculated. If this value is more than _minimum confidence_ value, the rule _A->B_ is added to the list.

In [326]:
def association_rules(min_confidence, min_lift, support_dict) -> pd.DataFrame:
    rules_data = []

    for itemset, support in support_dict.items():

        if len(itemset) < 2:
            continue

        for i in range(1, len(itemset)):
            for A in combinations(itemset, i):
                A = frozenset(A)
                B = itemset - A

                support_A = support_dict[A]
                support_B = support_dict[B]

                confidence = support / support_A
                lift = support / (support_A * support_B)

                if confidence >= min_confidence and lift >= min_lift:
                    rules_data.append(
                        {"A": A, "B": B, "Confidence": confidence, "Lift": lift}
                    )

    rules_df = pd.DataFrame(rules_data)
    return rules_df

### Specify a minimum confidence and lift value to generate the association rules.

In [334]:
min_confidence = 0.5
min_lift = 0
rules = association_rules(
    min_confidence=min_confidence,
    min_lift=min_lift,
    support_dict=item_support_dict,
)

In [336]:
import timeit
# benchmarking the association_rules function
time_taken_association_rules = timeit.timeit(
    lambda: association_rules(min_confidence, min_lift, item_support_dict),
    number=num_iterations,
)

print(
    f"Time taken for {num_iterations} iterations of association_rules: {time_taken_association_rules} seconds"
)

Time taken for 100 iterations of association_rules: 0.14365209999959916 seconds

In [328]:
print("Number of rules: ", len(rules), "\n")
rules

Number of rules:  53

,A,B,Confidence,Lift
0,"(almonds, carrots)",(burgers),0.571429,5.994805
1,"(almonds, chicken)",(burgers),0.555556,5.828283
2,"(almonds, cooking oil)",(chocolate),0.538462,5.664797
3,"(burgers, bug spray)",(chocolate),0.500000,5.260168
4,"(cake, cider)",(burgers),0.545455,5.722314
5,"(cooking oil, chili)",(chicken),0.714286,2.996564
6,"(chili, chicken)",(cooking oil),0.555556,8.885335
7,"(almonds, chicken, chocolate)",(burgers),0.500000,5.245455
8,"(cereals, almonds, chocolate)",(cake),0.666667,5.046081
9,"(cereals, almonds, cake)",(chocolate),0.666667,7.013558
10,"(cake, avocado, brownies)",(burgers),1.000000,10.490909
11,"(avocado, burgers, brownies)",(cake),0.750000,5.676842
12,"(brownies, avocado, chocolate)",(burgers),0.666667,6.993939
13,"(brownies, burgers, chocolate)",(avocado),0.500000,6.168586
14,"(avocado, burgers, brownies)",(chocolate),0.500000,5.260168
15,"(brownies, avocado, chocolate)",(cake),0.666667,5.046081
16,"(cake, avocado, brownies)",(chocolate),0.666667,7.013558
17,"(cake, burgers, avocado)",(chocolate),0.555556,5.844631
18,"(cake, avocado, chocolate)",(burgers),0.555556,5.828283
19,"(avocado, burgers, chocolate)",(cake),0.500000,3.784561
20,"(bacon, cooking oil, burgers)",(chicken),0.666667,2.796793
21,"(bacon, cooking oil, chicken)",(burgers),0.500000,5.245455
22,"(bacon, burgers, chicken)",(cooking oil),0.666667,10.662402
23,"(chocolate, burgers, brownies)",(cake),0.500000,3.784561
24,"(cake, cooking oil, brownies)",(burgers),0.666667,6.993939
25,"(cooking oil, burgers, brownies)",(cake),0.666667,5.046081
26,"(cake, cooking oil, butter)",(brownies),0.500000,2.925507
27,"(cake, cooking oil, brownies)",(butter),0.666667,12.724343
28,"(cake, butter, brownies)",(cooking oil),0.666667,10.662402
29,"(butter, cooking oil, brownies)",(cake),0.500000,3.784561
30,"(butter, cooking oil, chicken)",(brownies),0.600000,3.510608
31,"(butter, cooking oil, brownies)",(chicken),0.750000,3.146393
32,"(butter, chicken, brownies)",(cooking oil),1.000000,15.993603
33,"(cooking oil, chicken, brownies)",(butter),0.600000,11.451908
34,"(burgers, chicken, bug spray)",(chocolate),0.666667,7.013558
35,"(burgers, bug spray, chocolate)",(chicken),0.500000,2.097595
36,"(chicken, bug spray, chocolate)",(burgers),0.666667,6.993939
37,"(cake, butter, burgers)",(chocolate),0.500000,5.260168
38,"(cake, cider, burgers)",(chocolate),0.500000,5.260168
39,"(cake, cider, chocolate)",(burgers),1.000000,10.490909
40,"(cake, cookies, burgers)",(chocolate),0.600000,6.312202
41,"(cooking oil, burgers, chicken)",(chocolate),0.666667,7.013558
42,"(cake, cooking oil, butter)",(chicken),0.500000,2.097595
43,"(cooking oil, chili, chocolate)",(chicken),0.666667,2.796793
44,"(chili, chicken, chocolate)",(cooking oil),0.666667,10.662402
45,"(cake, avocado, brownies)","(burgers, chocolate)",0.666667,39.067708
46,"(chocolate, burgers, brownies)","(cake, avocado)",0.500000,117.203125
47,"(avocado, burgers, brownies)","(cake, chocolate)",0.500000,36.769608
48,"(chocolate, avocado, brownies)","(cake, burgers)",0.666667,58.147287
49,"(chocolate, cake, burgers, brownies)",(avocado),1.000000,12.337171
50,"(cake, burgers, avocado, brownies)",(chocolate),0.666667,7.013558
51,"(chocolate, cake, avocado, brownies)",(burgers),1.000000,10.490909
52,"(chocolate, avocado, burgers, brownies)",(cake),1.000000,7.569122